### ISSUE TITLE
"Mean requires at least one data point"

### ISSUE THREAD

**Issue by timniper** [andyco98/UTILE-Gen#3]
Good evening,

I am trying to use the Dataset_Gen function and keep getting the error "Mean requires at least one data point":

---------------------------------------------------------------------------------------------------------------------------------------------------
StatisticsError                           Traceback (most recent call last)
Cell In[4], line 7
      4 input_image_path = r"C:\Users\timni\OneDrive\Desktop\UTIL\images\1.png"
      5 input_mask_path = r"C:\Users\timni\OneDrive\Desktop\UTIL\masks\1.png"
----> 7 Dataset_Gen(1, 10, 10, input_mask_path, input_image_path, projectname, True, True, False, 0.2, 2, 0.3, 3)

File ~\OneDrive\Documents\GitHub\UTILE-Gen\UTILE-Gen Tool\DatasetGeneratorFunctions.py:525, in Dataset_Gen(dataset_size, l, u, input_mask_path, input_image_path, projectname, no, only_real, only_realbg, sp_amount, gb_amount, min_size, max_size)
    521     print("You do not have permissions to change to {0}".format(path))
    523 Remove_Zero_Values(input_image_path)
--> 525 GetBG(input_mask_path, input_image_path, projectname, only_realbg)
    527 if l > 2:
    528     input_mask_path = Eliminate_Edge_Pt(input_mask_path)

File ~\OneDrive\Documents\GitHub\UTILE-Gen\UTILE-Gen Tool\LabeltoROI.py:203, in GetBG(maskpath, imagepath, projectname, only_realbg)
    200     px_value = image_bg.item(y,x,1)
    201     bg_values.append(px_value)
--> 203 bg_mean = mean(bg_values)
    204 #print(round(bg_mean))
    205 new_bg = np.zeros((1350,1350,3),dtype=np.uint8)

File ~\anaconda3\envs\myenv\lib\statistics.py:315, in mean(data)
    313 n = len(data)
    314 if n < 1:
--> 315     raise StatisticsError('mean requires at least one data point')
    316 T, total, count = _sum(data)
    317 assert count == n

StatisticsError: mean requires at least one data point
---------------------------------------------------------------------------------------------------------------------------------------------------

Any idea on how to correct this?

Thanks

**Comment by andyco98** [comment]
Hi @timniper! From the first look, I think your error comes probably from the image that you are using. It seems that it cannot be read properly and for this, it cannot find any pixels. I will suggest two workarounds: 1. can you turn the flag "only real background" to True (it will first skip that part of the code, so we can see if it is an image problem or a code problem)?
If still does not work because of a similar error I would suggest being sure that your image is represented. Also the code is written for similar images to the ones depicted in figures here where you have your objects of interest represented with an individual value (e.g. cells, particles) and then the black background with value 0. Is that the case? :)

**Comment by timniper** [comment]
Hi @andyco98. It was a binary image issue for the mask. Simple fix. Thanks!

Now I am at another crossroads. Getting this error:
--------------------------------------------------------------------------------------------------------------------------------------------
Generating BG...
Done!
Generating mask...
Done!
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[2], line 7
      4 input_image_path = r"C:\Users\timni\OneDrive\Desktop\UTIL\images\1.tif"
      5 input_mask_path = r"C:\Users\timni\OneDrive\Desktop\UTIL\masks\1.tif"
----> 7 Dataset_Gen(1, 10, 20, input_mask_path, input_image_path, projectname, True, True, False, 0.2, 2, 0.3, 3)

File ~\OneDrive\Documents\GitHub\UTILE-Gen\UTILE-Gen Tool\DatasetGeneratorFunctions.py:536, in Dataset_Gen(dataset_size, l, u, input_mask_path, input_image_path, projectname, no, only_real, only_realbg, sp_amount, gb_amount, min_size, max_size)
    532 generate_label_pool(input_mask_path, input_image_path, projectname)
    534 img_pool = './test_image_pool_'+projectname+'/'
--> 536 Particle_To_Texture(img_pool, projectname, only_real)
    538 pt_pool = './test_mask_pool_'+projectname+'/'
    539 roi_tx_pool = './roi_txt_pool_'+projectname+'/'

File ~\OneDrive\Documents\GitHub\UTILE-Gen\UTILE-Gen Tool\DatasetGeneratorFunctions.py:169, in Particle_To_Texture(particle_image_pool, projectname, only_real)
    167 def Particle_To_Texture(particle_image_pool, projectname, only_real):    #extract the textures from the particles
--> 169     img_pool = os.listdir(particle_image_pool)
    170     w_pt = []
    171     h_pt = []

FileNotFoundError: [WinError 3] The system cannot find the path specified: './test_image_pool_Project1/'
------------------------------------------------------------------------------------------------------------------------------------

Do I need to add a path to my system variables? I do not even see an image_pool output folder tucked away anywhere. Sorry if these are easy questions, I am not the best at python. 

Thanks,
Tim

**Comment by andyco98** [comment]
Hi @timniper! Sorry for the late reply! It is not a problem since you are the first one trying to run this code externally! So from your error, something should go wrong in the code after extracting the particles into the particle pool folder with the ImageJ API. When you run the code, a folder with your project name should be created. Inside this folder, is there no test_image_pool folder? Every time you get an error try restarting the kernel and eliminating the files to start clean and avoid errors with the past generated files. Thanks for your comment!

**Comment by timniper** [comment]
Hi @andyco98. Not a problem!  I have done all your suggestions. Also re-cloned the repository to make sure everything was in order. Still getting the same error. I get the project name folder, but in it, there is no test_image_pool folder. The only things within the folder are:
ProjectD (Project Name Folder)
         *Background (Folder)
                         -background_ProjectD.png
                         -realbackground_ProjectD.png
         *mask.png

On a side note, when running (from DatasetGeneratorFunctions import *), there is a note that says "The headless flag of imagej.init is deprecated. Use the mode argument instead."             Is that relevant at all?

Thanks for all the help,
Tim

**Comment by andyco98** [comment]
Hi @timniper! We have reworked the pipeline so that ImageJ is no longer needed (what was priobably what made problems) adn now we tested it in several computers and has worked directly. Could you update the files and retry? It should work now :D Thanks a lot in advance! We appreciate a lot your testing :)

**Comment by timniper** [comment]
Hi @andyco98. Re-downloaded all the files. Unfortunately, I am still getting the same error:
FileNotFoundError: [WinError 3] The system cannot find the path specified: './test_image_pool_Project1/'

Should there be an os.mkdir('./test_image_pool_'+projectname+'/') somewhere within the code?

**Comment by andyco98** [comment]
Hmm, that is strange. Actually, in the file UTILE-Gen/UTILE-Gen Tool/LabeltoROI.py in lines 316-329, there is the os.mkdir line which creates the folder and afterward saves the data into it.  I uploaded an image and a mask that worked for me in order to see if the problem comes from there. Could you use it as a test image/mask? Are you running it from the cmd? Could you try doing it from an anaconda environment?  Bash and cmd handle paths in different manners; bash with "/" as separator and windows "\", so maybe that is the issue?

**Comment by timniper** [comment]
Alright. So I tried your images (Thanks), and made an environment in anaconda. Finally got past the directory problem. Now I get this:

-------------------------------------------------------------------------
Generating BG...
Done!
Generating mask...
Done!
---------------------------------------------------------------------------
FileExistsError                           Traceback (most recent call last)
Cell In[2], line 7
      4 input_image_path = r'C:\Users\timni\OneDrive\Desktop\UTIL\images\testimage1.tif'
      5 input_mask_path = r'C:\Users\timni\OneDrive\Desktop\UTIL\masks\testmask1.tif'
----> 7 Dataset_Gen(1, 10, 10, input_mask_path, input_image_path, projectname, True, True, False, 0.2, 2, 0.3, 3)

File ~\OneDrive\Documents\GitHub\UTILE-Gen\UTILE-Gen Tool\DatasetGeneratorFunctions.py:532, in Dataset_Gen(dataset_size, l, u, input_mask_path, input_image_path, projectname, no, only_real, only_realbg, sp_amount, gb_amount, min_size, max_size)
    528     input_mask_path = Eliminate_Edge_Pt(input_mask_path)
    531 #LabelToPool(input_mask_path, input_image_path, projectname)
--> 532 generate_label_pool(input_mask_path, input_image_path, projectname)
    534 img_pool = './test_image_pool_'+projectname+'/'
    536 Particle_To_Texture(img_pool, projectname, only_real)

File ~\OneDrive\Documents\GitHub\UTILE-Gen\UTILE-Gen Tool\LabeltoROI.py:317, in generate_label_pool(maskpath, imagepath, projectname)
    311 #old = "./test_mask_pool/"                    #changes the name of the file to a project specific name
    312 
    313 #old2 = "./test_image_pool/"
    314 #new2 = "./test_image_pool_"+ projectname +"/"
    316 if os.path.isfile(new_mask_pool) == False:
--> 317     os.mkdir(new_mask_pool)
    318 if os.path.isfile(new_image_pool) == False:
    319     os.mkdir(new_image_pool)

FileExistsError: [WinError 183] Cannot create a file when that file already exists: './test_mask_pool_MyEMimage1'
--------------------------------------------------------------------------------------------------------------------------------------------

I tried going back to some older code like:
--------------------------------------------------------------------------------------------------------------------------------------------
        old = "./test_mask_pool/"                    #changes the name of the file to a project specific name
        new = "./test_mask_pool_"+ projectname +"/"#

        old2 = "./test_image_pool/"
        new2 = "./test_image_pool_"+ projectname +"/"

        if os.path.isfile(old2) == False:
            os.mkdir(old2)
        if os.path.isfile(old) == False:
            os.mkdir(old)

#    macroscript = ij.py.run_script('ijm', macro, args)

        if os.path.isfile(new) == False:
            os.rename(old, "./test_mask_pool_"+ projectname +"/") #still have to fix the existing file problem
        if os.path.isfile(new2) == False:
            os.rename(old2, "./test_image_pool_"+ projectname +"/")#
        
        
       # image.save(new_image_pool + f'/image_{key}.png')
       # mask.convert("L").save(new_mask_pool + f'/image_{key}.png')
        image.save(new2 + f'/image_{key}.png')
        mask.convert("L").save(new + f'/image_{key}.png')
--------------------------------------------------------------------------------------------------------------------------------------------

but that did not work either.

**Comment by andyco98** [comment]
Hi @timniper! Nice, that we could advance! It is almost there, I promise! Please use only the newer code, restart the kernel of the jupyter notebook and remove the "old" folder (in this case MyEMimage1) or use a New project name. I think It should be all fine now :)

**Comment by timniper** [comment]
Hi @andyco98. Uninstalled and reinstalled the code. New project name. Same error.  Cannot create a file when that file already exists. We are getting there:)

**Comment by timniper** [comment]
It is as if the code is looping. The code makes the file, and then tries to make it again

**Comment by andyco98** [comment]
@timniper Thank you for your comment! I reinstalled it and started from scratch again from a new computer and I found the issue. It seems like some part of the code did not get updated but now it should be fixed. I corrected some issues with new libraries and put the folder creation code outside the loop ;) I hope this works now!

**Comment by timniper** [comment]
Hi @andyco98. It works! Thank you so much for the help!
